<Workspace Version="1.3.2.2480" X="157.048076177674" Y="10.2614320995451" zoom="0.594339614371454" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="d24f65ee-e735-4cc2-aad8-8fb5b00a9c83" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="RIE.IntersectionsFromListOfLines" x="258.709193420358" y="15.2029811095758" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="42e2c8c4-1dba-4a24-aaae-5f5a52f94a1f" />
      <Name value="RIE.IntersectionsFromListOfLines" />
      <Description value="Outputs points on which lines in a list intersect" />
      <Inputs>
        <Input value="Lines" />
      </Inputs>
      <Outputs>
        <Output value="Points" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Nodes.DSModelElementsSelection guid="03e3d315-04c1-453c-810d-25e072178de7" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-596.79064936962" y="-15.943399458661" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="2904eef8-0955-4a07-81b4-9018fe744f99-001634c2" />
      <instance id="2904eef8-0955-4a07-81b4-9018fe744f99-001634eb" />
      <instance id="2904eef8-0955-4a07-81b4-9018fe744f99-00163526" />
      <instance id="2904eef8-0955-4a07-81b4-9018fe744f99-00163553" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="8cb1971d-4534-4d85-81a3-8af66c2bdc7c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Intersect" x="-14.7206440574997" y="-180.68587589013" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Intersect@Autodesk.DesignScript.Geometry.Geometry">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="8f7c59a4-01f4-45b9-9407-34111b910be1" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.GetItemAtIndex" x="-311.006681000301" y="-189.147643844526" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.GetItemAtIndex@var[]..[],int">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="07e04a28-eae5-45d9-8c3b-4b7b85ba4879" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-456" y="-187" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="4a377d9e-c3d1-4cd5-921a-abca44d5c420" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="DetailCurve.Curve" x="-281.551159527501" y="27.8443530490297" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.DetailCurve.Curve">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9f84fad3-e0d4-4ecc-84dc-50fc481dea9a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="46.3249838214912" y="12.2661408882232" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="388a3585-5d51-401c-b0b1-e346ed894692" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.SolidIntersection" x="44.7702065470927" y="54.0486210995209" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="..\1.3\packages\bimorphNodes\bin\BimorphNodes.dll" function="Curve.SolidIntersection@Autodesk.DesignScript.Geometry.Solid,Autodesk.DesignScript.Geometry.Curve[],bool">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="fc453161-beb6-4669-9cb0-0db5056425b1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-98.9759652074422" y="735.367385885144" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
clr.AddReference('DSCoreNodes') 
import DSCore
from DSCore import *


#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0], list):
    lines = UnwrapElement(IN[0])
else:
    lines = [UnwrapElement(IN[0])]

OUT = []
pershape = []

def line_intersects(p1sp,p1ep,p2sp,p2ep):
	xdiff = (p1sp.X - p1ep.X, p2sp.X - p2ep.X)
	ydiff = (p1sp.Y - p1ep.Y, p2sp.Y - p2ep.Y)
	
	def det(a1,a2,b1,b2):
		return a1 * b2 - a2 * b1
	
	div = det(xdiff[0],xdiff[1],ydiff[0],ydiff[1])
	if div &lt;&gt; 0:
		d = (det(p1sp.X,p1sp.Y,p1ep.X,p1ep.Y), det(p2sp.X,p2sp.Y,p2ep.X,p2ep.Y))
		x = det(d[0],d[1], xdiff[0],xdiff[1]) / div
		y = det(d[0],d[1], ydiff[0],ydiff[1]) / div
		if x &gt; p1sp.X and x &lt; p1ep.X and y &gt; p2sp.Y and y &lt; p2ep.Y:
			return Point.ByCoordinates(x,y)
for f in range(0, len(lines)):			
	for l1 in lines:
		p1sp = l1.StartPoint 
		p1ep = l1.EndPoint
		data = []
		for l2 in lines:
			if l1 != l2:
				p2sp = l2.StartPoint
				p2ep = l2.EndPoint
				if  p1sp.X &lt; p2sp.X and p1ep.X &gt; p2ep.X  or p1sp.Y &gt; p2sp.Y and p1ep.Y &lt; p2ep.Y:
					if not (line_intersects(p1sp,p1ep,p2sp,p2ep) is None):
						data.append(line_intersects(p1sp,p1ep,p2sp,p2ep))
		if len(data) &gt; 0:
			pershape.append(data)
	if len(pershape) &gt; 0:
		OUT.append(pershape)
		pershape = []
	else:
		OUT.append('No intersections found')
		pershape = []</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="6a2de06f-1cd7-4414-b1ab-9ac406c0e6ae" type="PythonNodeModels.PythonNode" nickname="Python Script" x="200.691485290445" y="609.432416570029" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
OUT = 0</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="03e3d315-04c1-453c-810d-25e072178de7" start_index="0" end="8f7c59a4-01f4-45b9-9407-34111b910be1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="03e3d315-04c1-453c-810d-25e072178de7" start_index="0" end="8cb1971d-4534-4d85-81a3-8af66c2bdc7c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="03e3d315-04c1-453c-810d-25e072178de7" start_index="0" end="4a377d9e-c3d1-4cd5-921a-abca44d5c420" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8f7c59a4-01f4-45b9-9407-34111b910be1" start_index="0" end="8cb1971d-4534-4d85-81a3-8af66c2bdc7c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="07e04a28-eae5-45d9-8c3b-4b7b85ba4879" start_index="0" end="8f7c59a4-01f4-45b9-9407-34111b910be1" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a377d9e-c3d1-4cd5-921a-abca44d5c420" start_index="0" end="9f84fad3-e0d4-4ecc-84dc-50fc481dea9a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a377d9e-c3d1-4cd5-921a-abca44d5c420" start_index="0" end="fc453161-beb6-4669-9cb0-0db5056425b1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9f84fad3-e0d4-4ecc-84dc-50fc481dea9a" start_index="0" end="d24f65ee-e735-4cc2-aad8-8fb5b00a9c83" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="8e3f2010-8756-4c9a-b06a-6269f18e5cda" annotationText="New and Improved" left="-108.975965207442" top="653.367385885144" width="144" height="175" fontSize="30" InitialTop="735.367385885144" InitialHeight="123" TextblockHeight="72" backgrouund="#FFC1D676">
      <Models ModelGuid="fc453161-beb6-4669-9cb0-0db5056425b1" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>