<Workspace Version="1.3.3.4651" X="450.23908240824" Y="289.746517140453" zoom="0.729950825270785" ScaleFactor="1" Name="RIE.SpaceBoundaryLines" Description="Outputs Boundarylines of input Space elements" ID="98bf2bb4-fec4-45c3-87a9-eb9c403bbc34" Category="RIE.Geometry">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="828fc85b-a5ee-436e-85d0-bb6c529ecdb1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="204.323625545091" y="266.935928597599" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Spaces" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d165fc5c-36b3-4a9c-98da-1a8594057271" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1574.63209369602" y="262.187134694126" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="PerimeterLines" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d6ab99dd-2e9a-4e33-af05-a49bdcf0b887" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.MaximumItem" x="929.261171159274" y="461.379368621585" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.MaximumItem@var[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="021c9a61-1939-4b2e-9e50-7690dbe9bb01" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="IndexOf" x="1119.57848783567" y="340.626312523451" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="IndexOf@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f1be21b0-0dd6-49d7-a5c2-17cad93e4bc7" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Math.Sum" x="683.066085211774" y="408.542015929769" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.Math.Sum@double[]">
      <PortInfo index="0" default="False" useLevels="True" level="2" shouldKeepListStructure="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="71e60df2-fe7a-42b5-9596-0f1096603d42" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.GetItemAtIndex" x="1346.6467346289" y="264.499385852889" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.GetItemAtIndex@var[]..[],int">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="790965cf-a290-4e96-880c-55d84c04dd0d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.Length" x="477.640534025504" y="403.019823693579" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.Length">
      <PortInfo index="0" default="False" useLevels="True" level="2" shouldKeepListStructure="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="673dc1e6-7c37-4363-8a28-babba8694cbe" type="PythonNodeModels.PythonNode" nickname="Python Script" x="296.979522818705" y="266.890717242763" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

def tolist(obj):
	if isinstance(obj, list):
		return UnwrapElement(obj)
	else:
		return [UnwrapElement(obj)]

items = tolist(IN[0])

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
if int(app.VersionNumber) &gt; 2017: fullVersion = app.SubVersionNumber
else: fullVersion = str(app.VersionNumber)

version = int(app.VersionNumber)



elementlist = list()
curvelist = list()

for item in items:
	doc = item.Document
	calculator = SpatialElementGeometryCalculator(doc)
	options = Autodesk.Revit.DB.SpatialElementBoundaryOptions()
	# get boundary location from area computation settings
	boundloc = Autodesk.Revit.DB.AreaVolumeSettings.GetAreaVolumeSettings(doc).GetSpatialElementBoundaryLocation(SpatialElementType.Space)
	options.SpatialElementBoundaryLocation = boundloc
	#method #1 - get boundary segments
	
	try:
		for boundarylist in item.GetBoundarySegments(options):
			clist = list()
			for boundary in boundarylist:
				if version &gt; 2016:
					clist.append(boundary.GetCurve().ToProtoType())
				else:
					clist.append(boundary.Curve.ToProtoType())
			curvelist.append(clist)
	except:
		pass
	#method #2 - spatial element geometry calculator
	try:
		results = calculator.CalculateSpatialElementGeometry(item)
		for face in results.GetGeometry().Faces:
			blist = list()
			clist = list()
			for bface in results.GetBoundaryFaceInfo(face):
				blist.append(doc.GetElement(bface.SpatialBoundaryElement.HostElementId))
			elementlist.append(blist)
			curvelist.append(clist)
	except:
		pass	
	# write results to list

OUT = [x for x in curvelist if x]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f0c178ed-4637-47fe-a400-4e5bc0afa037" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1580.11191488605" y="325.205078379491" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="AllBoundaries" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="828fc85b-a5ee-436e-85d0-bb6c529ecdb1" start_index="0" end="673dc1e6-7c37-4363-8a28-babba8694cbe" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d6ab99dd-2e9a-4e33-af05-a49bdcf0b887" start_index="0" end="021c9a61-1939-4b2e-9e50-7690dbe9bb01" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="021c9a61-1939-4b2e-9e50-7690dbe9bb01" start_index="0" end="71e60df2-fe7a-42b5-9596-0f1096603d42" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f1be21b0-0dd6-49d7-a5c2-17cad93e4bc7" start_index="0" end="d6ab99dd-2e9a-4e33-af05-a49bdcf0b887" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f1be21b0-0dd6-49d7-a5c2-17cad93e4bc7" start_index="0" end="021c9a61-1939-4b2e-9e50-7690dbe9bb01" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="71e60df2-fe7a-42b5-9596-0f1096603d42" start_index="0" end="d165fc5c-36b3-4a9c-98da-1a8594057271" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="790965cf-a290-4e96-880c-55d84c04dd0d" start_index="0" end="f1be21b0-0dd6-49d7-a5c2-17cad93e4bc7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="673dc1e6-7c37-4363-8a28-babba8694cbe" start_index="0" end="71e60df2-fe7a-42b5-9596-0f1096603d42" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="673dc1e6-7c37-4363-8a28-babba8694cbe" start_index="0" end="790965cf-a290-4e96-880c-55d84c04dd0d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="673dc1e6-7c37-4363-8a28-babba8694cbe" start_index="0" end="f0c178ed-4637-47fe-a400-4e5bc0afa037" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="90098.7653431715" eyeY="35928.6276480426" eyeZ="-21979.5096744741" lookX="40.8818421275209" lookY="-35429.8414816986" lookZ="542.365123557705" upX="-0.0736548081040382" upY="0.199367940425873" upZ="-0.977152705192566" />
  </Cameras>
</Workspace>