<Workspace Version="1.3.3.4651" X="95" Y="114" zoom="1" ScaleFactor="1" Name="RIE.SetRevisionDescription" Description="Sets description of input revision" ID="cbbfc665-9fc0-421a-ada3-291c40c8b8fd" Category="RIE.Revisions">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="77d06f40-b0df-4cef-98a2-6963dc76b98c" type="PythonNodeModels.PythonNode" nickname="Python Script [Description]" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import sys
#pyt_path = r"C:\Program Files (x86)\IronPython 2.7\DLLs"
#sys.path.append(pyt_path)
import clr

#clr.AddReference('IronPython.SQLite.dll')
pyt_path = r"C:\Program Files (x86)\IronPython 2.7\Lib"
sys.path.append(pyt_path)
#import sqlite3

# Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument
app = DocumentManager.Instance.CurrentUIApplication.Application

# Import List ( ICollection(ElementId) = List[ElementId]() )
clr.AddReference('System')
from System.Collections.Generic import List

# Import Revit API + APIUI
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Electrical import *

clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import *

OUT = []

def tolist(obj):
	if isinstance(obj, list):
		return UnwrapElement(obj)
	else:
		return [UnwrapElement(obj)]

def setvalue(rev,description):
	rev.Description = description
	return description

TransactionManager.Instance.EnsureInTransaction(doc)

if isinstance(IN[1], list):
	if len(IN[1]) == len(IN[0]):
		for i,j in zip(tolist(IN[0]),tolist(IN[1])):
			OUT.append(setvalue(i,j))
	else:
		for i in tolist(IN[0]):
			OUT.append(setvalue(i,IN[1][0]))
else:
	for i in tolist(IN[0]):
		OUT.append(setvalue(i,IN[1]))
	
TransactionManager.Instance.TransactionTaskDone()
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4b3ea081-4131-4d6a-828e-0df36acac6c8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="133" y="1" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Revision" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3acd19a7-52de-47c5-bc2b-3fbc4f2987fb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="35" y="63" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Description : string" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d03367bb-d9b4-45d9-9616-1fc1862a5728" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="443" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Description" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="77d06f40-b0df-4cef-98a2-6963dc76b98c" start_index="0" end="d03367bb-d9b4-45d9-9616-1fc1862a5728" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4b3ea081-4131-4d6a-828e-0df36acac6c8" start_index="0" end="77d06f40-b0df-4cef-98a2-6963dc76b98c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3acd19a7-52de-47c5-bc2b-3fbc4f2987fb" start_index="0" end="77d06f40-b0df-4cef-98a2-6963dc76b98c" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>