<Workspace Version="1.3.3.4651" X="179.633683631108" Y="183.777868919197" zoom="1.545620359375" ScaleFactor="1" Name="RIE.LinkDocFromLink" Description="Retrieves link Document element from link element." ID="d04f09ff-a04d-42d6-980e-f9fc98e163df" Category="RIE.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="6a37d7f8-2683-4eb6-b69c-bce5debf4838" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Analysis import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

def tolist(obj):
	if isinstance(obj, list):
		return UnwrapElement(obj)
	else:
		return [UnwrapElement(obj)]

linkInstances = tolist(IN[0])

linkDoc = []
for i in linkInstances:
	linkDoc.append(i.GetLinkDocument())
if len(linkDoc) != 1:
	OUT = linkDoc
else:
	OUT = linkDoc[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e10cf7d6-c58e-44fa-8c46-ba1c7da62525" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="119.046050916671" y="0.646989407155843" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="LinkInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="047506b3-bf72-463a-9829-aba2c9bc9e23" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="376.537186398548" y="-0.646989407155814" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="LinkDoc" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6a37d7f8-2683-4eb6-b69c-bce5debf4838" start_index="0" end="047506b3-bf72-463a-9829-aba2c9bc9e23" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e10cf7d6-c58e-44fa-8c46-ba1c7da62525" start_index="0" end="6a37d7f8-2683-4eb6-b69c-bce5debf4838" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>