<Workspace Version="1.3.3.4651" X="-308" Y="153" zoom="1" ScaleFactor="1" Name="RIE.ElementsIntersectingElement" Description="Retrieves all elements intersecting with input element. Can be linked elements as well as local elements." ID="96799478-2a78-4500-aa19-d490de60ad0f" Category="RIE.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="f618ed0b-0213-4b84-9a57-eeba1f79c73a" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="RIE.LinkDocFromLink" x="713" y="120.996689552464" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="d04f09ff-a04d-42d6-980e-f9fc98e163df" />
      <Name value="RIE.LinkDocFromLink" />
      <Description value="Retrieves link Document element from link element." />
      <Inputs>
        <Input value="LinkInstance" />
      </Inputs>
      <Outputs>
        <Output value="LinkDoc" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="17b80450-ee41-498b-8ab0-f955b75d7189" type="PythonNodeModels.PythonNode" nickname="Python Script" x="971.437810623403" y="79.9724408945781" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># RETRIEVED FROM EINAR RAKNES ON THE DYNAMOBIM.ORG FORUMS.

import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitNodes')
clr.AddReference('RevitServices')
import Revit
import RevitServices
from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument

if IN[1] != None:
	doc = UnwrapElement(IN[1])

def tolist(obj):
	if isinstance(obj,list):
		return UnwrapElement(obj)
	else:
		return [UnwrapElement(obj)]

#Preparing input from dynamo to revit
els = tolist(IN[0])
OUT = []

for el in els:
	elems = []

	filter = ElementIntersectsElementFilter(el)
	
	collector = FilteredElementCollector(doc).WherePasses(filter)
	
	elems = [e.ToDSType(True) for e in collector]
	OUT.append(elems)
if len(OUT) == 1:
	OUT = OUT[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="88b03c3c-b1d8-4abc-89b0-a7b106c92acd" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1099.53031631062" y="79" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a64c1e02-637e-4c63-a72e-3efe27b9e755" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="857" y="58" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b25316ad-bbc0-46d3-9699-71c2ec6a86f7" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="452" y="121" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="LinkOptional : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f618ed0b-0213-4b84-9a57-eeba1f79c73a" start_index="0" end="17b80450-ee41-498b-8ab0-f955b75d7189" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="17b80450-ee41-498b-8ab0-f955b75d7189" start_index="0" end="88b03c3c-b1d8-4abc-89b0-a7b106c92acd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a64c1e02-637e-4c63-a72e-3efe27b9e755" start_index="0" end="17b80450-ee41-498b-8ab0-f955b75d7189" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b25316ad-bbc0-46d3-9699-71c2ec6a86f7" start_index="0" end="f618ed0b-0213-4b84-9a57-eeba1f79c73a" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>