<Workspace Version="1.3.3.4651" X="169.27372215625" Y="356.231231961755" zoom="1.545620359375" ScaleFactor="1" Name="RIE.SetRevisionIssued" Description="Sets input revision to issued or not issued based on true/false input" ID="f0d3e578-47ab-4b26-b3d6-5a98c520f43c" Category="RIE.Revisions">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="fb2d666c-5260-4f59-9a6a-9884018410c2" type="PythonNodeModels.PythonNode" nickname="Python Script [Issued]" x="155.53954655525" y="-1.94096822146747" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import sys
#pyt_path = r"C:\Program Files (x86)\IronPython 2.7\DLLs"
#sys.path.append(pyt_path)
import clr

#clr.AddReference('IronPython.SQLite.dll')
pyt_path = r"C:\Program Files (x86)\IronPython 2.7\Lib"
sys.path.append(pyt_path)
#import sqlite3

# Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument
app = DocumentManager.Instance.CurrentUIApplication.Application

# Import List ( ICollection(ElementId) = List[ElementId]() )
clr.AddReference('System')
from System.Collections.Generic import List

# Import Revit API + APIUI
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Electrical import *

clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import *

OUT = []

def tolist(obj):
	if isinstance(obj, list):
		return UnwrapElement(obj)
	else:
		return [UnwrapElement(obj)]

def setvalue(rev,yesno):
	rev.Issued = yesno
	return yesno

TransactionManager.Instance.EnsureInTransaction(doc)

if isinstance(IN[1], list):
	if len(IN[1]) == len(IN[0]):
		for i,j in zip(tolist(IN[0]),tolist(IN[1])):
			OUT.append(setvalue(i,j))
	else:
		for i in tolist(IN[0]):
			OUT.append(setvalue(i,IN[1][0]))
else:
	for i in tolist(IN[0]):
		OUT.append(setvalue(i,IN[1]))
	
TransactionManager.Instance.TransactionTaskDone()
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3eaddeff-c0dc-4286-92f8-ec8823467749" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="47.8772161295308" y="-1.29397881431169" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Revision" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a9f5ba58-4076-42cd-b7d9-d128682346af" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-27.1735551005445" y="53.5985783337825" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Bool : bool=false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a8bb31cc-ae78-4179-91bd-add041977992" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="307.311679989577" y="5.6843418860808E-14" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="fb2d666c-5260-4f59-9a6a-9884018410c2" start_index="0" end="a8bb31cc-ae78-4179-91bd-add041977992" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3eaddeff-c0dc-4286-92f8-ec8823467749" start_index="0" end="fb2d666c-5260-4f59-9a6a-9884018410c2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a9f5ba58-4076-42cd-b7d9-d128682346af" start_index="0" end="fb2d666c-5260-4f59-9a6a-9884018410c2" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>