<Workspace Version="1.3.3.4111" X="-491.268295927866" Y="167.081151344703" zoom="1.78359936238281" ScaleFactor="1" Name="RIE.BBoxFromPlanView" Description="Retrieves boundingbox from active view based on viewrange settins" ID="126a1507-c041-42f4-a6a2-9da67711b13a" Category="RIE.Geometry">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="dab01be9-d88b-4206-9f79-90a81dcdd221" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1299.58683090223" y="222.699484463992" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="BBox" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="78a9232d-3f53-40ed-8143-6b1452df576a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="298.586830902235" y="204.699484463992" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Views" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="334ebed7-5239-4940-b8a8-d840765808c4" type="PythonNodeModels.PythonNode" nickname="Python Script" x="469.586830902235" y="204.699484463992" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr





clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import*

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager
import System
from System.Collections.Generic import *

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import*
from Autodesk.Revit.DB import FilteredElementCollector, RevitLinkType

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]
	
ft = 304.8

doc = DocumentManager.Instance.CurrentDBDocument
UIunit = Document.GetUnits(doc).GetFormatOptions(UnitType.UT_Length).DisplayUnits

OUT = []

if IN[0] == None:
	views = tolist(doc.ActiveView)
else:
	views = tolist(UnwrapElement(IN[0]))

for v in views:
	bb = v.CropBox
	vr = v.GetViewRange()
	topclip = PlanViewPlane.TopClipPlane
	bottomclip = PlanViewPlane.BottomClipPlane
	cutclip = PlanViewPlane.CutPlane
	toplevel = (doc.GetElement(vr.GetLevelId(topclip)))
	topoffset = vr.GetOffset(topclip)
	cutlevel = (doc.GetElement(vr.GetLevelId(cutclip)))
	cutoffset = vr.GetOffset(cutclip)
	try:
		topZ = toplevel.Elevation + topoffset
	except:
		topZ = cutlevel.Elevation + cutoffset
		bottomlevel = (doc.GetElement(vr.GetLevelId(bottomclip)))
		bottomoffset = vr.GetOffset(bottomclip)
	try:
		bottomZ = bottomlevel.Elevation + bottomoffset
	except :
		bottomZ = cutlevel.Elevation
		min = bb.Min
		max = bb.Max
		newmin = XYZ(UnitUtils.ConvertToInternalUnits(min.X,UIunit)*ft,UnitUtils.ConvertToInternalUnits(min.Y,UIunit)*ft,bottomZ)
		newmax = XYZ(UnitUtils.ConvertToInternalUnits(max.X,UIunit)*ft,UnitUtils.ConvertToInternalUnits(max.Y,UIunit)*ft,topZ)
		#OUT.append(Outline(newmin,newmax).ToRevitType())
		OUT.append([newmin.ToPoint(),newmax.ToPoint()])</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="5a994f89-4ebf-4115-bff5-0a6a8468de02" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="469.586830902235" y="288.126151130659" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0;&#xA;1;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b872ab19-7151-4afe-9e49-0e6bb085726b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.GetItemAtIndex" x="693.586830902235" y="168.699484463992" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.GetItemAtIndex@var[]..[],int">
      <PortInfo index="0" default="False" useLevels="True" level="2" shouldKeepListStructure="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2f6b2740-94cc-4c0d-b564-5cea898b3fc3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.GetItemAtIndex" x="693.586830902235" y="302.699484463992" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.GetItemAtIndex@var[]..[],int">
      <PortInfo index="0" default="False" useLevels="True" level="2" shouldKeepListStructure="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="00de462f-2b5c-44b0-87b3-398ba86276d4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="BoundingBox.ByCorners" x="972.586830902235" y="222.699484463992" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.BoundingBox.ByCorners@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="78a9232d-3f53-40ed-8143-6b1452df576a" start_index="0" end="334ebed7-5239-4940-b8a8-d840765808c4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="334ebed7-5239-4940-b8a8-d840765808c4" start_index="0" end="b872ab19-7151-4afe-9e49-0e6bb085726b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="334ebed7-5239-4940-b8a8-d840765808c4" start_index="0" end="2f6b2740-94cc-4c0d-b564-5cea898b3fc3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5a994f89-4ebf-4115-bff5-0a6a8468de02" start_index="0" end="b872ab19-7151-4afe-9e49-0e6bb085726b" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5a994f89-4ebf-4115-bff5-0a6a8468de02" start_index="1" end="2f6b2740-94cc-4c0d-b564-5cea898b3fc3" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b872ab19-7151-4afe-9e49-0e6bb085726b" start_index="0" end="00de462f-2b5c-44b0-87b3-398ba86276d4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2f6b2740-94cc-4c0d-b564-5cea898b3fc3" start_index="0" end="00de462f-2b5c-44b0-87b3-398ba86276d4" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="00de462f-2b5c-44b0-87b3-398ba86276d4" start_index="0" end="dab01be9-d88b-4206-9f79-90a81dcdd221" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="90333.8972682639" eyeY="139563.022725199" eyeZ="79403.9328477925" lookX="-10505.9031276389" lookY="-110813.022725199" lookZ="-103238.161363417" upX="-0.0573434706697731" upY="0.824126188622015" upZ="-0.563496008503073" />
  </Cameras>
</Workspace>