<Workspace Version="1.3.3.4651" X="-22.5667442743394" Y="273.331870150393" zoom="2.72962159758084" ScaleFactor="1" Name="RIE.EquipmentFromCircuits" Description="Returns Equipment connected to input circuit" ID="588a5709-8dee-48b5-a6e3-6dc22af51381" Category="RIE.Power">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="05eef59a-3612-4a91-adfd-4d0f8d2278ff" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># @ Copyright - Designed by Andr√© Abotnes andre.abotnes@norconsult.com
import sys
#pyt_path = r"C:\Program Files (x86)\IronPython 2.7\DLLs"
#sys.path.append(pyt_path)
import clr

#clr.AddReference('IronPython.SQLite.dll')
pyt_path = r"C:\Program Files (x86)\IronPython 2.7\Lib"
sys.path.append(pyt_path)
#import sqlite3

# Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument
app = DocumentManager.Instance.CurrentUIApplication.Application

# Import List ( ICollection(ElementId) = List[ElementId]() )
clr.AddReference('System')
from System.Collections.Generic import List

# Import Revit API + APIUI
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Electrical import *

clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import *

OUT = []

def tolist(obj):
	if isinstance(obj, list):
		return UnwrapElement(obj)
	else:
		return [UnwrapElement(obj)]

# Start Transaction
# TransactionManager.Instance.EnsureInTransaction(doc)

# End Transaction
# TransactionManager.Instance.TransactionTaskDone()

systems = tolist(IN[0])
elements = []
	

if hasattr(systems[0],'__iter__'):
	newlist = []
	elements = []
	for x in systems:
		collection = []
		for y in x:
			newlist = []
			try:
				for z in y.Elements:
					newlist.append(z)
			except:
				if y.IsEmpty:
					newlist.append(y.Category.Name)
				else:
					newlist.append("Failed")
			collection.append(newlist)
		elements.append(collection)
	
else:
	for x in systems:
		sublist = []
		try:
			elementset = x.Elements
			for x in elementset:
				sublist.append(x)
		except:
			if x.IsEmpty:
				sublist.append(x.Category.Name)
			else:
				sublist.append("Failed")
		elements.append(sublist)

#Assign your output to the OUT variable.
OUT = elements
if len(OUT) == 1:
	OUT = OUT[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b8b35b10-e91b-422c-bd2b-5759f859fc71" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="146.906809484286" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Circuits" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4dd8d273-8cff-4b17-b7c3-ed0e0d006d9c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="380.858686872626" y="-0.366351145846096" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Equipment" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="05eef59a-3612-4a91-adfd-4d0f8d2278ff" start_index="0" end="4dd8d273-8cff-4b17-b7c3-ed0e0d006d9c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b8b35b10-e91b-422c-bd2b-5759f859fc71" start_index="0" end="05eef59a-3612-4a91-adfd-4d0f8d2278ff" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>