<Workspace Version="1.3.3.4651" X="1212.75871830767" Y="384.620801476068" zoom="1.545620359375" ScaleFactor="1" Name="RIE.Point.SpaceAndRoom" Description="Gets Spaces and Rooms containing the point from the input points list." ID="7aea7722-b9f0-411f-8af2-9722ccb7322c" Category="RIE.Geometry">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="dc0d8d62-8167-45f2-a878-ac84d40d9d5a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="252.249121906482" y="6.33194139809876" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Electrical import *

clr.AddReference('DSCoreNodes')
import DSCore
from DSCore.List import *

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

doc = DocumentManager.Instance.CurrentDBDocument
if IN[1] != None:
	doc = IN[1]
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

OUT = []
spaces = []
rooms = []

def tolist(input):
	if isinstance(input, list):
		return input
	else:
		return [input]

for _ in tolist(IN[0]):
	pt = UnwrapElement(_)
	if doc.GetSpaceAtPoint(pt.ToXyz()) == None:
		spaces.append("No Space")
	else:
		spaces.append(doc.GetSpaceAtPoint(pt.ToXyz()))
	if doc.GetRoomAtPoint(pt.ToXyz()) == None:
		rooms.append("No Room")
	else:
		rooms.append(doc.GetRoomAtPoint(pt.ToXyz()))

OUT = spaces, rooms</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="dc83b957-0ca9-4c52-8115-1b9b2913270c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="161.88667068683" y="-34.428391252718" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Points" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e2aac414-b5f3-4b80-9f50-abdeaa8b284d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="483.79810908854" y="-31.7861221589663" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Spaces" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2f05b253-2cba-4c5f-8f43-556eb5e6dc7f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="483.79810908854" y="52.2138778410337" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Rooms" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="9810a6a0-7125-40cf-9705-6965870302b7" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="392.787488383381" y="-30.8077358614121" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="4d2713eb-0688-45ad-bb1f-a692e51cee01" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="392.787488383381" y="53.1922641385879" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="922fa617-1f6d-4e25-8608-ca6f60988f68" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="RIE.LinkDocFromLink" x="-23.1355119585288" y="43.1470183925466" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="d04f09ff-a04d-42d6-980e-f9fc98e163df" />
      <Name value="RIE.LinkDocFromLink" />
      <Description value="Retrieves link Document element from link element." />
      <Inputs>
        <Input value="LinkInstance" />
      </Inputs>
      <Outputs>
        <Output value="LinkDoc" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5dad75e5-bed6-4d89-b248-2d0542b76545" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-670.124919114351" y="46.1815853362565" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Optional. If no Link Instance is input, Current Document will be used.&#xD;&#xA;LinkOptional : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="dc0d8d62-8167-45f2-a878-ac84d40d9d5a" start_index="0" end="4d2713eb-0688-45ad-bb1f-a692e51cee01" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dc0d8d62-8167-45f2-a878-ac84d40d9d5a" start_index="0" end="9810a6a0-7125-40cf-9705-6965870302b7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dc83b957-0ca9-4c52-8115-1b9b2913270c" start_index="0" end="dc0d8d62-8167-45f2-a878-ac84d40d9d5a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9810a6a0-7125-40cf-9705-6965870302b7" start_index="0" end="e2aac414-b5f3-4b80-9f50-abdeaa8b284d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4d2713eb-0688-45ad-bb1f-a692e51cee01" start_index="0" end="2f05b253-2cba-4c5f-8f43-556eb5e6dc7f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="922fa617-1f6d-4e25-8608-ca6f60988f68" start_index="0" end="dc0d8d62-8167-45f2-a878-ac84d40d9d5a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5dad75e5-bed6-4d89-b248-2d0542b76545" start_index="0" end="922fa617-1f6d-4e25-8608-ca6f60988f68" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>