<Workspace Version="1.3.2.2480" X="179.388742279676" Y="413.351017592165" zoom="1.21316139457394" ScaleFactor="1" Name="3DView.BoundryBox" Description="Takes in a 3D View and outputs the views scope box as a boundry box" ID="33a53cf0-2418-4c87-aee9-394ffebc2fe9" Category="Dan's Nodes">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="e7a0bd20-52c4-4e04-9ffd-cb5e62a23b1f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="806.295303762919" y="20.2702065078022" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


views = UnwrapElement(IN[0])

TransactionManager.Instance.EnsureInTransaction(doc)

viewlist = []
sectionboxes = []
floors = []
floorboxes = []

for view in views:
	viewlist.append(view)
	sectionbox = view.GetSectionBox()
	transform = sectionbox.Transform
	sboxoriginx = transform.Origin.X
	sboxoriginy = transform.Origin.Y
	sboxoriginz = transform.Origin.Z
	minx = sectionbox.Min.X + sboxoriginx
	maxx = sectionbox.Max.X + sboxoriginx
	miny = sectionbox.Min.Y + sboxoriginy
	maxy = sectionbox.Max.Y + sboxoriginy
	minz = sectionbox.Min.Z + sboxoriginz
	maxz = sectionbox.Max.Z + sboxoriginz
	bbox = BoundingBoxXYZ()
	bbox.Min = XYZ((minx), (miny), (minz))
	bbox.Max = XYZ((maxx), (maxy), (maxz))
	tsectionbox = bbox.ToProtoType()
	sectionboxes.append(tsectionbox)
	collector = FilteredElementCollector(doc, view.Id)
	floor = collector.OfClass(Floor).ToElements()
	floors.append(floor)

TransactionManager.Instance.TransactionTaskDone()

OUT = views, sectionboxes, floors</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="540064d2-37f7-44d2-aae2-e288a54c7491" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="3DView" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="63037cb2-7ac7-4d40-bc8c-36c58da2a046" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1421.68042533159" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <CoreNodeModels.CreateList guid="e771c3f6-915b-4e25-b2b9-78be5b6409e8" type="CoreNodeModels.CreateList" nickname="List.Create" x="539.014505829237" y="1.90041178643537" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </CoreNodeModels.CreateList>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="bf8e6f08-a96e-4442-8ce9-042748d26156" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="777" y="-152" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="1;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="77b0e3c3-f13b-446c-981c-9c607bfd97cf" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="987" y="-112" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="92486ef0-a79f-4566-ab3f-a0a3c3eb75ae" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.GetItemAtIndex" x="1219.66366643638" y="92.0340322122798" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.GetItemAtIndex@var[]..[],int">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="8c45a541-08c9-41bd-bad3-9734cf1337e9" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.GetItemAtIndex" x="985.109029129242" y="98.703832325279" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.GetItemAtIndex@var[]..[],int">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e7a0bd20-52c4-4e04-9ffd-cb5e62a23b1f" start_index="0" end="8c45a541-08c9-41bd-bad3-9734cf1337e9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="540064d2-37f7-44d2-aae2-e288a54c7491" start_index="0" end="e771c3f6-915b-4e25-b2b9-78be5b6409e8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="540064d2-37f7-44d2-aae2-e288a54c7491" start_index="0" end="e771c3f6-915b-4e25-b2b9-78be5b6409e8" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e771c3f6-915b-4e25-b2b9-78be5b6409e8" start_index="0" end="e7a0bd20-52c4-4e04-9ffd-cb5e62a23b1f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bf8e6f08-a96e-4442-8ce9-042748d26156" start_index="0" end="8c45a541-08c9-41bd-bad3-9734cf1337e9" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="77b0e3c3-f13b-446c-981c-9c607bfd97cf" start_index="0" end="92486ef0-a79f-4566-ab3f-a0a3c3eb75ae" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="92486ef0-a79f-4566-ab3f-a0a3c3eb75ae" start_index="0" end="63037cb2-7ac7-4d40-bc8c-36c58da2a046" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8c45a541-08c9-41bd-bad3-9734cf1337e9" start_index="0" end="92486ef0-a79f-4566-ab3f-a0a3c3eb75ae" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="c0573faf-37e6-420f-99ce-3a1dac8650b4" annotationText="Multiple views" left="796.295303762919" top="-61.7297934921978" width="144" height="150" fontSize="30" InitialTop="20.2702065078022" InitialHeight="123" TextblockHeight="72" backgrouund="#FFC1D676">
      <Models ModelGuid="e7a0bd20-52c4-4e04-9ffd-cb5e62a23b1f" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-101.59162902832" eyeY="63.3104820251465" eyeZ="176.472946166992" lookX="110.84162902832" lookY="-16.3920593261719" lookZ="-183.097946166992" upX="-0.072073332965374" upY="0.990268051624298" upZ="0.119057074189186" />
  </Cameras>
</Workspace>